### ISSUE TITLE
More informative error message when configuration is invalid

### ISSUE THREAD

**Issue by RolandKluge** [se-passau/SPLConqueror#35]
In a configuration file, I have an invalid "all <data-file>" specification.
Instead of reporting that the configuration is not valid or cannot be read, I received an "InvalidArgumentException"

The location is here:
* File: CommandLine -> Commands.cs
* Line: 432
* Expression: ConfigurationReader.readConfigurations(task.TrimEnd(), GlobalState.varModel)
  * Returned ```null``` in my case.

It would be good to have a more expressive exception here that states that the 'task' does not represent a valid configuration.

**Comment by DonHok** [comment]
More informative messages added by https://github.com/se-passau/SPLConqueror/commit/8ea8ea2203955562205d74aa68452cd69a12afce

**Comment by RolandKluge** [comment]
Thanks and Merry Christmas :-)
