### ISSUE TITLE
Hint at VS 2017 in README.md

### ISSUE THREAD

**Issue by RolandKluge** [se-passau/SPLConqueror#36]
I tried to compile SPLC with VS 2013, which did not work because SPLC uses C#7 features (e.g., ```import static```).

Could you extend you instructions in the README.md file regarding VS 2017 being required?

**Comment by DonHok** [comment]
Added Visual Studio 2015 or newer as recommendation, as it can still be compiled with command line build tools like MSBuild and xbuild or other IDEs like Rider.
