### ISSUE TITLE
Document usage of git submodule

### ISSUE THREAD

**Issue by RolandKluge** [se-passau/SPLConqueror#38]
In my workspace, I previously had a version of SPLC that contained a 'hard copy' of ViPe.

Now, ViPe is inserted via the git submodule mechanism.

Could you document that it is necessary to pull also the submodules?

In my case, it was enough to do the following:
```
git submodule update --init --recursive
```

Probably, people cloning a fresh copy of SPLC will not have this problem, but I wanted to remark this anyway.

**Comment by ChristianKaltenecker** [comment]
Hey,

Thank you for opening this issue.
Yes, you are right. Since ViPe became a public repository and will receive several updates in the future, we have removed the hard copy and inserted it as a git submodule.

I have added the respective command to the documentation.
