### ISSUE TITLE
Some features are not taken into account

### ISSUE THREAD

**Issue by martinpfannemueller** [se-passau/SPLConqueror#41]
After SPLC finished learning, the result only takes some of the features into account. Does this mean, that it could not find an interaction between these features and the corresponding non-functional property or is this typically rather a problem of my encoding? Or, as I limit the time for learning to one hour: Does it make sense to let the learning process simply run longer although we typically had good results with the one hour time limit?

Referring to #40, I tried both solutions described there.

**Comment by martinpfannemueller** [comment]
Thanks a lot for your explanations, I will try your suggestions and will also take a look at the visualization. The strange thing is, that the attributes which are attached to the feature which does not appear in the result are part of the PIM. This hierarchy is correctly stated in the variability model. Thus, when the feature is not part of the PIM, the attributes are irrelevant and should not be part of the PIM as well or not?

**Comment by ChristianKaltenecker** [comment]
Hey,

Sorry for the late response.

**withHierachy**:
The option `withHierarchy` is related to the way how the performance-influence model is learned.

> When the feature is not part of the PIM, the attributes are irrelevant and should not be part of the PIM as well or not?

No. The attributes of the feature may also appear. When performing machine learning, we do not consider the information from the variability model.

**Comment by martinpfannemueller** [comment]
Hi,

Thanks, this clarifies it a lot. I was not sure if the information of the VM is taken into account here and I though it is strange to have the attributes in the PIM and not the actual feature.
